// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRtA6_zGYX6JAj7FtxFuwvSaMVqMVkRN0',
    appId: '1:694730504476:web:cb92d875bca5d1f468a2d9',
    messagingSenderId: '694730504476',
    projectId: 'shared-calendar-bf9c0',
    authDomain: 'shared-calendar-bf9c0.firebaseapp.com',
    storageBucket: 'shared-calendar-bf9c0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUehe35Oy7bDHWEC-zHNZj9mDqKRx2JoA',
    appId: '1:694730504476:android:cee957a0f2a5c0e368a2d9',
    messagingSenderId: '694730504476',
    projectId: 'shared-calendar-bf9c0',
    storageBucket: 'shared-calendar-bf9c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHLGx_clae2SHLYsYpR1PrjN2ZDfVmo5E',
    appId: '1:694730504476:ios:d4ff58cd8366f4ce68a2d9',
    messagingSenderId: '694730504476',
    projectId: 'shared-calendar-bf9c0',
    storageBucket: 'shared-calendar-bf9c0.firebasestorage.app',
    iosBundleId: 'com.example.sharedCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHLGx_clae2SHLYsYpR1PrjN2ZDfVmo5E',
    appId: '1:694730504476:ios:d4ff58cd8366f4ce68a2d9',
    messagingSenderId: '694730504476',
    projectId: 'shared-calendar-bf9c0',
    storageBucket: 'shared-calendar-bf9c0.firebasestorage.app',
    iosBundleId: 'com.example.sharedCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRtA6_zGYX6JAj7FtxFuwvSaMVqMVkRN0',
    appId: '1:694730504476:web:f670600dc8febcb968a2d9',
    messagingSenderId: '694730504476',
    projectId: 'shared-calendar-bf9c0',
    authDomain: 'shared-calendar-bf9c0.firebaseapp.com',
    storageBucket: 'shared-calendar-bf9c0.firebasestorage.app',
  );

}